export default {
    primaryColor: '#EF4344',
    secondaryColor: '#FF793F',
    tertiaryColor: '#DA2123',
    backgroundColor: '#FFFFFF',
    foregroundColor: '#000000',
    foregroundAlternate: '#FFFFFF',
    regularFont: 'Inter_400Regular',
    strongFont: 'Inter_600SemiBold',
    headerFont: 'Inter_Display_600SemiBold',
    monospaceFont: 'RobotoMono_400Regular',
    waveAmplitude: 0.2,
    lighterForeground: '#EEEEEE',
    lightForeground: '#CCCCCC',
    darkForeground: '#666',
    warning: '#F9AF40',
    darkerWarning: '#f89c12',
    darkerPrimary: '#bc1010',
};
